title: Ivan Jurić # your name (or website title) here
logo: "/images/profilna.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <b>Age<b/>: 26
   <br>
 <b>Place<b/>: Zagreb
  <br><br>
  Done is better than perfect.
  If you want to make something fun, have fun making it.
  <br><br>
  <a href="https://www.artstation.com/juki11">View My Artstation Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
