title: Ivan Jurić # your name (or website title) here
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
<b>ABOUT</b>
  <br>
 I primarily work as a VFX Artist, creating visual effects in Unreal Engine and Unity.
 While my main focus is VFX, I also have experience with C#, HLSL, 2D art, and animation to a certain extent. In Unity, I handle both VFX and programming, leveraging my technical understanding to optimize and implement effects efficiently.
 I enjoy combining art and tech to bring dynamic visuals to life!
 <br>
   <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  <b>SKILLS</b>
  <br>
VFX
  <br>
  C#
   <br>
   Shader graph
   <br>
   HLSL
   <br>
   2D art
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  
   <b>Shipped Titles</b>
   <br>
   <a href="https://store.playstation.com/en-hr/product/EP7345-PPSA20372_00-0018074913236815" target="_blank">Cosmic Paradox: Noire</a>
   <br>
   <a href="https://store.playstation.com/en-hr/product/EP7345-PPSA26549_00-0349027590004907" target="_blank">Magnitude</a>
   <br>
   <a href="https://store.playstation.com/en-hr/product/EP7345-PPSA27913_00-0818032948658132" target="_blank">Magnitude: Epsilon</a>
   <br>
      <a href="https://store.playstation.com/en-hr/product/EP7345-PPSA28264_00-0540415989288772" target="_blank">Puzzle Piecer: The World Below</a>
   <br>

   <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
 
  <b>TOOLS</b>
  <br>
  Adobe Photoshop
  <br>
  Krita
  <br>
  Procreate
  <br>
  Blender
  <br>
  Substance Designer
  <br>
  Unity
  <br>
  Unreal Engine
  <br>
  EmberGen
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  <b>DETAILS</b>
  <br>
  Zagreb,Croatia
  <br>
  +385 95 896 5148
  <br>
  iv.juric95@gmail.com
  <br><br>
