title: Ivan Jurić # your name (or website title) here
logo: "/images/profilna.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 A passionate artist and coder
  <br><br>
 
  <b>SKILLS</b>
  <br>
  Digital art
  <br>
  C#
  <hr style="height:2px;border-width:0;color:gray;background-color:#f5bf42">
  <br><br>
 
  <b>TOOLS</b>
  <br>
  Adobe Photoshop
  <br>
  Procreate
  <br>
  Blender
  <br>
  Substance Designer
  <br>
  Unity
  <br>
  Unreal Engine
  <br>
  EmberGen
  <hr style="height:2px;border-width:0;color:gray;background-color:#f5bf42">
  <br><br>
   <b>INTERESTED IN</b>
  <br>
  Real time VFX
  <br>
  Prop art
  <br>
  Coding
  <hr style="height:2px;border-width:0;color:gray;background-color:#f5bf42">
  <br><br>
  <b>DETAILS</b>
  <br>
  Zagreb,Croatia
  <br>
  +385 95 896 5148
  <br>
  iv.juric95@gmail.com
  <br><br>
  
  
theme: jekyll-theme-minimal
