title: Ivan Jurić # your name (or website title) here
logo: "/images/profilna.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <b>Profile</b>
 <br>
 A passionate artist, coder and new technologies enthusiast.
 <br><br>
 <b>Age</b>: 26
   <br>
 <b>Place</b>: Zagreb
  <br><br>
 
  <b>Skills</b>
  C#
  <br>
  Adobe Photoshop
  <br>
  After effects
  <br>
  Procreate
  <br>
  Houdini
  <br>
  Blender
  <br>
  Vuforia
  <br>
  AR Foundation
  <br><br>
  
  <a href="https://www.artstation.com/juki11">View My Artstation Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
