title: Ivan Jurić # your name (or website title) here
logo: "/images/profilna.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br>
 A passionate artist and coder
  <br><br>
 
  <b>Skills</b>
  <br>
  C# 
  .dot {
  height: 25px;
  width: 25px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
}
<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>
  <br>
  2D Digital art
  Adobe Photoshop
  <br>
  Procreate
  <br>
  Blender
  <br>
  Substance Designer
  <br><br>
  <b>DETAILS</b>
  <br>
  Zagreb,Croatia
  <br>
  +385 95 896 5148
  <br>
  iv.juric95@gmail.com
  <br><br>
  
  
theme: jekyll-theme-minimal
