title: Ivan Jurić # your name (or website title) here
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
<b>ABOUT</b>
  <br>
 <br>
   <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  <b>SKILLS</b>
  <br>
VFX
  <br>
  C#
   <br>
   Shader graph
   <br>
   HLSL
   <br>
   2D art
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  
  

   <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
 
  <b>TOOLS</b>
  <br>
  Adobe Photoshop
  <br>
  Krita
  <br>
  Procreate
  <br>
  Blender
  <br>
  Substance Designer
  <br>
  Unity
  <br>
  Unreal Engine
  <br>
  EmberGen
  <hr style="height:2px;border-width:0;color:gray;background-color:#4b72b4">
  <b>DETAILS</b>
  <br>
  Zagreb,Croatia
  <br>
  +385 95 896 5148
  <br>
  iv.juric95@gmail.com
  <br><be>


theme: jekyll-theme-minimal
